import { notFound } from 'next/navigation';
import { Header, Contact, Footer } from '../../shared';
import { services, enquiry } from '../services';
export function generateStaticParams(){return services.map(s=>({service:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{service:string}>}){const {service}=await params;const s=services.find(s=>s.slug===service);return {title:s?`${s.name} — Shalik Visual`:'Service not found',description:s?.summary}}
export default async function Service({params}:{params:Promise<{service:string}>}){
 const {service}=await params;const s=services.find(s=>s.slug===service);if(!s)notFound();
 return <><Header/><main><section className="section offer-hero"><a className="eyebrow" href="/#offer">← ALL SERVICES</a><div className="offer-hero-grid"><div><p className="eyebrow offer-accent">{s.name.toUpperCase()}</p><h1>{s.headline}</h1></div><div><p className="offer-lead">{s.summary}</p><p>{s.audience}</p><a className="pill dark" href={enquiry(s.name)}>Discuss your project ↗</a></div></div><nav className="service-sections" aria-label="On this page"><a href="#included">What’s included</a><a href="#examples">Our work</a><a href="#process">The process</a><a href="#pricing">Pricing</a><a href="#case-study">Example case study</a></nav></section>
 <section className="section offer-split" id="included"><div><span className="eyebrow">01 / THE SCOPE</span><h2>What we can<br/>take care of.</h2><p>Build the right scope for your project. Your quote confirms the final deliverables, schedule and included review rounds.</p></div><ol className="included-list">{s.includes.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></section>
 <section className="section service-work" id="examples"><div className="heading-row"><div><span className="eyebrow">02 / OUR WORK</span><h2>A feel for our craft.</h2></div><p>Explore our production showreel.<br/>For examples relevant to your brief, get in touch.</p></div><video controls playsInline preload="none" poster="/media/frame-1.jpg" src="/media/showreel.mp4?v=25-26" aria-label="Shalik Visual production showreel"/><div className="card-label"><h3>Shalik Visual / Production showreel</h3><a href={enquiry(s.name)}>Request relevant work ↗</a></div></section>
 <section className="section" id="process"><span className="eyebrow">03 / HOW WE WORK TOGETHER</span><h2 className="service-heading">From your brief<br/>to the final delivery.</h2><ol className="process-grid">{s.steps.map((step,i)=><li key={step}><span className="process-number">0{i+1}</span><h3>{['Start with a conversation','Agree the plan','Create together','Review & deliver'][i]}</h3><p>{step}</p></li>)}</ol></section>
 <section className="section pricing-section offer-split" id="pricing"><div><span className="eyebrow">04 / PRICING</span><h2>A clear scope.<br/>A tailored quote.</h2><p>Every project has different production needs. Send us your brief and budget range so we can propose a scope that fits.</p></div><div className="quote-panel"><span className="eyebrow">{s.name.toUpperCase()}</span><h3>Price on request</h3><p><strong>What shapes the budget</strong><br/>{s.factors}</p><p><strong>Before production starts</strong><br/>We agree deliverables, usage rights, schedule, review rounds and any additional costs in the quote.</p><a className="pill dark" href={enquiry(s.name)}>Get a project quote ↗</a></div></section>
 <section className="section" id="case-study"><span className="eyebrow">05 / EXAMPLE CASE STUDY</span><div className="heading-row"><h2>How it could<br/>come together.</h2><p>Illustrative project scenario.<br/>Not a completed client project or a results claim.</p></div><div className="case-grid">{[['The brief',s.brief],['The approach',s.approach],['The deliverables',s.delivery]].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="section other-services"><span className="eyebrow">EXPLORE OTHER SERVICES</span><div>{services.filter(x=>x.slug!==s.slug).map(x=><a href={'/offer/'+x.slug} key={x.slug}>{x.name} ↗</a>)}</div></section><Contact/></main><Footer/></>
}
