'use client';
import FobosVideo from '@/components/fobos-video';
import { useEffect, useRef, useState } from 'react';
import { Header, Contact, Footer } from './shared';
import { services } from './offer/services';
import { clientNames } from './partners/names';
export default function Home(){
 const video=useRef<HTMLVideoElement>(null); const [playing,setPlaying]=useState(true); const [sound,setSound]=useState(false);
 useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){video.current?.pause();setPlaying(false)}},[]);
 return <><Header/><main><section className="hero"><video ref={video} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} autoPlay muted={!sound} loop playsInline poster="/media/frame-1.jpg" src="/media/showreel.mp4?v=25-26"/><div className="shade"/><div className="hero-top"><span className="eyebrow"><i/> NIEZALEŻNY DOM PRODUKCYJNY</span><span className="eyebrow">FILM. DŹWIĘK. EMOCJE.</span></div><div className="hero-title"><h1>TWÓRZMY<br/><em>Z SENSEM.</em></h1><div className="hero-bottom"><p>Zmieniamy pomysły w obrazy, które zostają w pamięci.<br/>Od pierwszej inspiracji po ostatnie cięcie.</p><div className="player-controls"><button onClick={()=>{if(!video.current)return; if(playing)video.current.pause();else void video.current.play().catch(()=>setPlaying(false));}}>{playing?"Ⅱ Zatrzymaj":"▶ Odtwórz"}</button><button onClick={()=>setSound(!sound)}>{sound?"Dźwięk włączony":"Dźwięk wyłączony"}</button></div></div></div><div className="hero-caption"><span>SHALIK VISUAL — SHOWREEL</span><a href="#work">ZOBACZ WIĘCEJ ↓</a></div></section>
<section id="work" className="section work"><div className="section-head"><span className="eyebrow">01 / W KADRZE</span><span className="eyebrow">FRAGMENT NASZEGO ŚWIATA</span></div><div className="heading-row"><h2>Obrazy, które<br/><span>mają coś do powiedzenia.</span></h2><p>Wybrane realizacje. Historie, które ożywają.<br/>Różne historie. Ta sama ciekawość.</p></div><div className="work-grid"><article className="work-card card-1"><FobosVideo/><div className="card-label"><h3>01 / Fobos - Balerina</h3><a href="/pl/offer/music-videos#case-study">Teledysk · Poznaj realizację ↗</a></div></article>{[2,3,4,5].map((n)=><article className={'work-card work-placeholder card-'+n} key={n}><div className="image-wrap"><span className="placeholder-number" aria-hidden="true">{String(n).padStart(2,'0')}</span><span className="placeholder-note">REALIZACJA WKRÓTCE</span></div><div className="card-label"><h3>Wybrana realizacja / {String(n).padStart(2,'0')}</h3><span>WKRÓTCE</span></div></article>)}</div></section>
<section className="section clients-section" id="clients"><div className="section-head"><span className="eyebrow">KLIENCI I PARTNERZY</span><a href="/pl/partners">Poznaj naszych partnerów ↗</a></div><h2>Dobre towarzystwo.<br/><span>Wielkie możliwości.</span></h2><ul className="client-names">{clientNames.map(name=><li key={name}>{name}</li>)}</ul><p>Pomysły zyskują siłę, gdy spotykają się właściwi ludzie.</p></section>
<section className="section offer-overview" id="offer"><span id="about" className="legacy-anchor" aria-hidden="true"/><div className="section-head"><span className="eyebrow">02 / NASZA OFERTA</span><span className="eyebrow">OD PIERWSZEGO POMYSŁU PO GOTOWY MATERIAŁ</span></div><div className="heading-row"><h2>Twój kolejny projekt.<br/><span>Nasza kreatywność i doświadczenie.</span></h2><p>Wprowadź produkt. Opowiedz historię. Rozpocznij rozmowę.<br/>Wybierz usługę dopasowaną do swojego celu.</p></div><div className="offer-list">{services.map((s,i)=><a className="offer-row" href={"/pl/offer/"+s.slug} key={s.slug}><span className="eyebrow">0{i+1}</span><h3>{s.name}</h3><p>{s.summary}</p><span className="offer-arrow" aria-hidden="true">↗</span></a>)}</div><div className="offer-team"><p>Dziewięć kreatywnych osób. Jeden zespół, który zadba o Twoją produkcję.</p><a className="pill" href="/pl/team">Poznaj nasz zespół ↗</a></div></section>
<section className="studio-promo"><div className="studio-word" aria-hidden="true">STUDIO<span>↗</span></div><div className="studio-promo-bottom"><div><span className="eyebrow">03 / MIEJSCE NA TWÓJ KOLEJNY POMYSŁ</span><h2>Twoja wizja.<br/>Nasza przestrzeń.</h2></div><div><p>Miejsce, w którym Twoja produkcja nabierze życia.<br/>Poznaj studio Shalik Visual i porozmawiajmy o Twojej kolejnej sesji.</p><a className="pill dark" href="/pl/studio">Poznaj studio <span>↗</span></a></div></div></section><Contact/></main><Footer/></>
}
