import { readFileSync } from 'node:fs';
import ts from 'typescript';
import assert from 'node:assert/strict';
const js=ts.transpileModule(readFileSync('lib/contact.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {handleContact}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const data={name:'Test Client',email:'client@example.com',message:'I would like to discuss a photography session.',id:'12345678-1234-4234-8234-123456789012',locale:'en',website:''};
const req=(body=data,origin='https://example.test')=>new Request('https://example.test/api/contact',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
const config={RESEND_API_KEY:'test-only',CONTACT_FROM_EMAIL:'Studio <studio@example.com>'};
let calls=0;
const send=async(url,options)=>{calls++;assert.equal(url,'https://api.resend.com/emails');const mail=JSON.parse(options.body);assert.deepEqual(mail.to,['kontakt@shalik.pl']);assert.equal(mail.reply_to,data.email);assert.ok(mail.text.includes(data.message));assert.equal(options.headers['Idempotency-Key'],'contact-'+data.id);return Response.json({id:'provider-test-id'})};
assert.equal((await handleContact(req({...data,email:'bad'}),config,send)).status,400);
assert.equal((await handleContact(req({...data,message:'short'}),config,send)).status,400);
assert.equal((await handleContact(req({...data,website:'spam'}),config,send)).status,400);
assert.equal((await handleContact(req(data,'https://foreign.test'),config,send)).status,403);
assert.equal((await handleContact(req({...data,message:'x'.repeat(25000)}),config,send)).status,413);
assert.equal((await handleContact(req(),{},send)).status,503);
assert.equal(calls,0);
assert.equal((await handleContact(req(),config,send)).status,200);
assert.equal(calls,1);
assert.equal((await handleContact(req(),config,async()=>Response.json({error:'provider error'},{status:429}))).status,502);
assert.equal((await handleContact(req(),config,async()=>Response.json({}))).status,502);
assert.equal((await handleContact(req(),config,async()=>{throw new Error('offline')})).status,502);
console.log('Contact tests passed: validation, origin, size limits, configuration, delivery payload, idempotency and provider failures. No email sent.');
