'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { usePathname } from 'next/navigation';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
const copy = {
 en: { title: 'Tell us what you have in mind.', intro: 'A film, a photo session, a podcast or something entirely new. Tell us what you want to create.', name: 'Your name', email: 'Email address', message: 'What would you like to create?', hint: 'Tell us what interests you, your goals and any dates or budget you have in mind.', placeholder: 'I’m interested in…', send: 'Send enquiry', sending: 'Sending…', checking: 'Checking availability…', draft: 'Open email draft', fallback: 'Online sending is currently unavailable. You can fill in the form and open an email draft to send from your email app.', opened: 'Your email app should open with your message. Review it and press Send there. Nothing has been sent by this website.', error: 'We couldn’t submit your enquiry. Your message is still here—please try again, or send it by email.', invalid: 'Please enter your name, a valid email address and a message of at least 10 characters.', success: 'Thank you! Your enquiry has been submitted. We’ll reply to the email address you provided.', another: 'Write another message', note: 'We’ll use these details to respond to your enquiry.', direct: 'Or email us directly', emailDraft: 'Send this message by email', subject: 'Project enquiry', count: 'characters' },
 pl: { title: 'Opowiedz nam o swoim pomyśle.', intro: 'Film, sesja zdjęciowa, podcast albo coś zupełnie nowego. Napisz, co chcesz stworzyć.', name: 'Imię i nazwisko', email: 'Adres e-mail', message: 'Co chcesz zrealizować?', hint: 'Napisz, co Cię interesuje, jaki masz cel oraz czy znasz już termin lub budżet.', placeholder: 'Interesuje mnie…', send: 'Wyślij zapytanie', sending: 'Wysyłanie…', checking: 'Sprawdzanie dostępności…', draft: 'Otwórz wiadomość e-mail', fallback: 'Wysyłanie bezpośrednio ze strony jest obecnie niedostępne. Wypełnij formularz, a otworzymy gotową wiadomość w Twoim programie pocztowym.', opened: 'Program pocztowy powinien otworzyć Twoją wiadomość. Sprawdź ją i kliknij w nim Wyślij. Strona nie wysłała wiadomości.', error: 'Nie udało się przesłać zapytania. Treść została zachowana — spróbuj ponownie lub wyślij ją e-mailem.', invalid: 'Podaj imię i nazwisko, prawidłowy adres e-mail oraz wiadomość o długości co najmniej 10 znaków.', success: 'Dziękujemy! Twoje zapytanie zostało przesłane. Odpowiemy na podany adres e-mail.', another: 'Napisz kolejną wiadomość', note: 'Wykorzystamy te dane, aby odpowiedzieć na Twoje zapytanie.', direct: 'Możesz też napisać bezpośrednio', emailDraft: 'Wyślij tę wiadomość e-mailem', subject: 'Zapytanie o projekt', count: 'znaków' },
};
export default function ContactForm() {
 const path = usePathname() || '/'; const locale = path === '/pl' || path.startsWith('/pl/') ? 'pl' : 'en'; const t = copy[locale];
 const [available,setAvailable] = useState<boolean|null>(null);
 const [values,setValues] = useState({name:'',email:'',message:'',website:''});
 const [state,setState] = useState<'idle'|'sending'|'success'|'error'|'opened'|'invalid'>('idle');
 const id = useRef(''); const busy = useRef(false);
 useEffect(()=>{const controller = new AbortController();fetch('/api/contact',{signal:controller.signal}).then(r=>r.ok?r.json():{available:false}).then(data=>setAvailable(Boolean(data && typeof data === 'object' && 'available' in data && data.available === true))).catch(()=>{if(!controller.signal.aborted)setAvailable(false)});return ()=>controller.abort()},[]);
 function change(field: keyof typeof values,value:string){setValues(v=>({...v,[field]:value}));id.current='';setState('idle')}
 function openDraft(){const text=`${t.name}: ${values.name}\n${t.email}: ${values.email}\n\n${values.message}`;window.location.href=`mailto:kontakt@shalik.pl?subject=${encodeURIComponent(t.subject)}&body=${encodeURIComponent(text)}`;setState('opened')}
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault(); if(busy.current)return;
  if(!values.name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim()) || values.message.trim().length<10){setState('invalid');return}
  if(!available){openDraft();return}
  busy.current=true;setState('sending');id.current ||= crypto.randomUUID();
  try {const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,locale,id:id.current}),signal:AbortSignal.timeout(20000)});const result=await response.json();if(response.ok && result && typeof result === 'object' && 'accepted' in result && result.accepted===true){setState('success');setValues({name:'',email:'',message:'',website:''});id.current=''}else{if(response.status===503)setAvailable(false);setState('error')}}catch{setState('error')}finally{busy.current=false}
 }
 return <div className="contact-form-layout"><div className="contact-form-intro"><h2>{t.title}</h2><p>{t.intro}</p><p>{t.direct}<br/><a href="mailto:kontakt@shalik.pl">kontakt@shalik.pl</a></p></div><form className="enquiry-form" onSubmit={submit} aria-label={t.title}>
 {state==='success'?<div className="form-success" role="status"><p>{t.success}</p><button type="button" className="pill" onClick={()=>setState('idle')}>{t.another}</button></div>:<><fieldset disabled={state==='sending'}><div className="form-pair"><label htmlFor="enquiry-name">{t.name}<Input id="enquiry-name" name="name" autoComplete="name" required maxLength={100} value={values.name} onChange={e=>change('name',e.target.value)}/></label><label htmlFor="enquiry-email">{t.email}<Input id="enquiry-email" name="email" type="email" autoComplete="email" required maxLength={254} value={values.email} onChange={e=>change('email',e.target.value)}/></label></div><label htmlFor="enquiry-message">{t.message}<Textarea id="enquiry-message" name="message" required minLength={10} maxLength={5000} rows={6} placeholder={t.placeholder} aria-describedby="message-hint message-count" value={values.message} onChange={e=>change('message',e.target.value)}/></label><div className="message-details"><p id="message-hint">{t.hint}</p><span id="message-count">{values.message.length}/5000 {t.count}</span></div><div className="form-trap" aria-hidden="true"><label htmlFor="enquiry-website">Website<Input id="enquiry-website" name="website" tabIndex={-1} autoComplete="off" value={values.website} onChange={e=>change('website',e.target.value)}/></label></div></fieldset>
 {available===false && <p className="form-notice">{t.fallback}</p>}
 <div className="form-actions"><button className="form-submit" type="submit" disabled={available===null || state==='sending'}>{state==='sending'?t.sending:available===null?t.checking:available?t.send:t.draft}<span aria-hidden="true">↗</span></button><p>{t.note}</p></div>
 <div aria-live="polite" aria-atomic="true">{state==='error'&&<p className="form-error">{t.error} <button type="button" onClick={openDraft}>{t.emailDraft}</button></p>}{state==='invalid'&&<p className="form-error">{t.invalid}</p>}{state==='opened'&&<p className="form-notice">{t.opened}</p>}</div></>}
 </form></div>
}
