'use client';
import { useEffect, useRef, useState } from 'react';
import { Header, Contact, Footer } from './shared';
import MusicVideo from '@/components/music-video';
import { services } from './offer/services';
import { clientNames } from './partners/names';
export default function Home(){
 const video=useRef<HTMLVideoElement>(null); const [playing,setPlaying]=useState(true); const [sound,setSound]=useState(false);
 useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){video.current?.pause();setPlaying(false)}},[]);
 return <><Header/><main><section className="hero"><video ref={video} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} autoPlay muted={!sound} loop playsInline poster="/media/frame-1.jpg" src="/media/showreel.mp4"/><div className="shade"/><div className="hero-top"><span className="eyebrow"><i/> INDEPENDENT PRODUCTION HOUSE</span><span className="eyebrow">FILM. SOUND. FEELING.</span></div><div className="hero-title"><h1>MAKE IT<br/><em>MEAN SOMETHING.</em></h1><div className="hero-bottom"><p>We turn ideas into images that stay with you.<br/>From the first spark to the final cut.</p><div className="player-controls"><button onClick={()=>{if(!video.current)return; if(playing)video.current.pause();else void video.current.play().catch(()=>setPlaying(false));}}>{playing?'Ⅱ Pause reel':'▶ Play reel'}</button><button onClick={()=>setSound(!sound)}>{sound?'Sound on ↗':'Sound off ↗'}</button></div></div></div><div className="hero-caption"><span>SHALIK VISUAL — SHOWREEL</span><a href="#work">SCROLL TO EXPLORE ↓</a></div></section>
<section id="work" className="section work"><div className="section-head"><span className="eyebrow">01 / IN FRAME</span><span className="eyebrow">A GLIMPSE OF OUR WORLD</span></div><div className="heading-row"><h2>Images with<br/><span>something to say.</span></h2><p>Music videos and moments from our showreel.<br/>Different stories. The same curiosity.</p></div><MusicVideo title="Music video / Selected work" label="Explore music video production" href="/offer/music-videos"/><div className="work-grid">{[1,2,3].map((n)=><a className={'work-card card-'+n} href={'/media/showreel.mp4#t='+[5,20,35][n-1]} key={n}><div className="image-wrap"><img src={'/media/frame-'+n+'.jpg'} alt={'Frame from the Shalik Visual production showreel, excerpt '+n}/><span className="play">↗</span></div><div className="card-label"><h3>Showreel / {String(n).padStart(2,'0')}</h3><span>SELECTED MOMENTS</span></div></a>)}</div></section>
<section className="section clients-section" id="clients"><div className="section-head"><span className="eyebrow">CLIENTS & PARTNERS</span><a href="/partners">Meet our partners ↗</a></div><h2>Good company.<br/><span>Great possibilities.</span></h2><ul className="client-names">{clientNames.map(name=><li key={name}>{name}</li>)}</ul><p>Ideas become stronger when the right people come together.</p></section>
<section className="section offer-overview" id="offer"><span id="about" className="legacy-anchor" aria-hidden="true"/><div className="section-head"><span className="eyebrow">02 / OUR OFFER</span><span className="eyebrow">FROM FIRST IDEA TO FINAL DELIVERY</span></div><div className="heading-row"><h2>Your next project.<br/><span>Our creative expertise.</span></h2><p>Launch a product. Tell a story. Start a conversation.<br/>Find the production service that fits your goal.</p></div><div className="offer-list">{services.map((s,i)=><a className="offer-row" href={'/offer/'+s.slug} key={s.slug}><span className="eyebrow">0{i+1}</span><h3>{s.name}</h3><p>{s.summary}</p><span className="offer-arrow" aria-hidden="true">↗</span></a>)}</div><div className="offer-team"><p>Nine creatives. One team to bring your production together.</p><a className="pill" href="/team">Meet our team ↗</a></div></section>
<section className="studio-promo"><div className="studio-word" aria-hidden="true">STUDIO<span>↗</span></div><div className="studio-promo-bottom"><div><span className="eyebrow">03 / ROOM FOR YOUR NEXT IDEA</span><h2>Your vision.<br/>Our space.</h2></div><div><p>A place to bring your production to life.<br/>Explore the Shalik Visual studio and talk to us about your next session.</p><a className="pill dark" href="/studio">Explore the studio <span>↗</span></a></div></div></section><Contact/></main><Footer/></>
}
