'use client';
import WhaiVideo from '@/components/whai-video';
import MotoVideo from '@/components/moto-video';
import CobinVideo from '@/components/cobin-video';
import FobosVideo from '@/components/fobos-video';
import { useEffect, useRef, useState } from 'react';
import { Header, Contact, Footer } from './shared';
import { services } from './offer/services';
import { clientNames } from './partners/names';
export default function Home(){
 const [clientsPaused,setClientsPaused]=useState(false);
 const video=useRef<HTMLVideoElement>(null); const [playing,setPlaying]=useState(true); const [sound,setSound]=useState(false);
 useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){video.current?.pause();setPlaying(false)}},[]);
 return <><Header/><main><section className="hero"><video ref={video} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} autoPlay muted={!sound} loop playsInline poster="/media/frame-1.jpg" src="/media/showreel.mp4?v=25-26"/><div className="shade"/><div className="hero-top"><span className="eyebrow"><i/> INDEPENDENT PRODUCTION HOUSE</span><span className="eyebrow">FILM. SOUND. FEELING.</span></div><div className="hero-title"><h1>MAKE IT<br/><em>MEAN SOMETHING.</em></h1><div className="hero-bottom"><p>We turn ideas into images that stay with you.<br/>From the first spark to the final cut.</p><div className="player-controls"><button onClick={()=>{if(!video.current)return; if(playing)video.current.pause();else void video.current.play().catch(()=>setPlaying(false));}}>{playing?'Ⅱ Pause reel':'▶ Play reel'}</button><button onClick={()=>setSound(!sound)}>{sound?'Sound on ↗':'Sound off ↗'}</button></div></div></div><div className="hero-caption"><span>SHALIK VISUAL — SHOWREEL</span><a href="#work">SCROLL TO EXPLORE ↓</a></div></section>

<section id="work" className="section work"><div className="section-head"><span className="eyebrow">01 / IN FRAME</span><span className="eyebrow">A GLIMPSE OF OUR WORLD</span></div><div className="heading-row"><h2>Images with<br/><span>something to say.</span></h2><p>Selected work. Stories brought to life.<br/>Different stories. The same curiosity.</p></div><div className="work-grid"><article className="work-card card-1"><FobosVideo/><div className="card-label"><h3>01 / Fobos - Balerina</h3><a href="/offer/music-videos#case-study">Music video · View case study ↗</a></div></article><article className="work-card card-2"><CobinVideo/><div className="card-label"><h3>02 / Business Angel of The Year - Cobin Angels</h3><a href="/offer/event-films#case-study">Event film · View case study ↗</a></div></article><article className="work-card card-3"><div className="fobos-player"><iframe src="https://www.youtube.com/embed/r8Si-gEjlQE" title="Interview with DJ Phinova" width="560" height="315" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div className="card-label"><h3>03 / Interview with DJ Phinova</h3><span>INTERVIEW</span></div></article><article className="work-card card-4"><MotoVideo/><div className="card-label"><h3>04 / V Jubileuszowy Moto Piknik na Bobrowym Rozlewisku 2026</h3><a href="/offer/event-films#moto-case-study">Event film · View case study ↗</a></div></article><article className="work-card card-5"><WhaiVideo/><div className="card-label"><h3>05 / WHAI Podcast Episode</h3><a href="/offer/editing-post-production#case-study">Post-production · View case study ↗</a></div></article></div></section>

<section className="section offer-overview" id="offer"><span id="about" className="legacy-anchor" aria-hidden="true"/><div className="section-head"><span className="eyebrow">02 / OUR OFFER</span><span className="eyebrow">FROM FIRST IDEA TO FINAL DELIVERY</span></div><div className="heading-row"><h2>Your next project.<br/><span>Our creative expertise.</span></h2><p>Launch a product. Tell a story. Start a conversation.<br/>Find the production service that fits your goal.</p></div><div className="offer-list">{services.map((s,i)=><a className="offer-row" href={'/offer/'+s.slug} key={s.slug}><span className="eyebrow">0{i+1}</span><h3>{s.name}</h3><p>{s.summary}</p><span className="offer-arrow" aria-hidden="true">↗</span></a>)}</div><div className="offer-team"><p>Nine creatives. One team to bring your production together.</p><a className="pill" href="/team">Meet our team ↗</a></div></section>
<section className="section clients-section" id="clients"><div className="section-head"><span className="eyebrow">OUR CLIENTS</span><a href="/partners">Clients &amp; Partners ↗</a></div><h2>Trusted by.</h2><p>Meet the clients who have trusted us with their projects.</p><div className="clients-marquee" data-paused={clientsPaused}><div className="clients-track">{[0,1].map(copy=><ul className="clients-strip" key={copy} aria-hidden={copy===1 ? true : undefined}>{clientNames.map(name=><li key={name}>{name}</li>)}</ul>)}</div></div><button type="button" className="clients-motion" aria-pressed={clientsPaused} onClick={()=>setClientsPaused(!clientsPaused)}>{clientsPaused?'▶ Resume client animation':'Ⅱ Pause client animation'}</button></section>
<section className="section network-preview"><div><span className="eyebrow">OUR BUSINESS NETWORK</span><h2>Connections that<br/><span>open possibilities.</span></h2><p>We are members of the PKB and BNI business clubs. These communities connect us with people, perspectives and opportunities for collaboration.</p><a className="text-link" href="/partners#network">Explore our network ↗</a></div><div className="network-badges" aria-label="Business club memberships"><span>PKB<small>Business club member</small></span><span>BNI<small>Business club member</small></span></div></section>
<section className="studio-promo"><div className="studio-word" aria-hidden="true">STUDIO<span>↗</span></div><div className="studio-promo-bottom"><div><span className="eyebrow">03 / ROOM FOR YOUR NEXT IDEA</span><h2>Your vision.<br/>Our space.</h2></div><div><p>A place to bring your production to life.<br/>Explore the Shalik Visual studio and talk to us about your next session.</p><a className="pill dark" href="/studio">Explore the studio <span>↗</span></a></div></div></section><section className="section talent-promo"><div><span className="eyebrow">FACES &amp; TALENT</span><h2>130+ people.<br/><span>Your next cast.</span></h2></div><div><p>Actors, singers, dancers, voice actors and extras. Tell us who your production needs—we’ll help you find suitable people.</p><div className="relationship-actions"><a className="pill" href="/talent#casting">Find talent ↗</a><a className="text-link" href="/talent#join">Join our database ↗</a></div></div></section><Contact/></main><Footer/></>
}
