import Image from 'next/image';
import ContactForm from '@/app/contact-form';
import StudioInstagram from './studio-instagram';
export default function StudioContent({locale='en'}:{locale?:'en'|'pl'}){
 const t=(en:string,pl:string)=>locale==='pl'?pl:en;
 const equipment=[
 [t('Flash lighting','Lampy błyskowe'),['1× Godox DP1000III-V 1000 Ws','1× Godox DP400III-V','1× Godox TT350 Speedlite',t('2× Godox X2T triggers','2× wyzwalacz Godox X2T')]],
 [t('GlareOne · LED & modifiers','GlareOne · LED i modyfikatory'),['1× GlareOne LED 600D 5600K',t('1× 90 cm octagonal softbox','1× softbox oktogonalny 90 cm'),t('1× 65 cm octagonal softbox / Beauty Dish','1× softbox oktogonalny 65 cm / Beauty Dish'),t('2× softbox grids','2× plaster miodu do softboxu'),t('4× colour filters','4× filtry kolorowe'),t('1× barn doors with grid','1× wrota z plastrem miodu')]],
 [t('Godox · LED & modifiers','Godox · LED i modyfikatory'),['2× Godox Litemons LA150Bi Bi-Color','2× Godox Softbox 60 × 90 cm',t('2× lightweight stands','2× lekki statyw')]],
 [t('LED & RGB lighting','Oświetlenie LED i RGB'),[t('2× 64 cm RGB LED tubes','2× miecz LED RGB 64 cm'),t('1× 24 cm RGB LED tube','1× miecz LED RGB 24 cm'),t('1× bi-colour LED panel','1× panel LED Bi-Color'),t('1× SmallRig RF 10C RGB light','1× latarka LED RGB SmallRig RF 10C'),t('1× colour gel set','1× zestaw folii kolorowych')]],
 [t('Light projection','Strumienica i projekcja światła'),['1× Spotlight 20°',t('16× effect masks / gobos','16× maska efektowa / gobo')]],
 [t('Effects & extras','Efekty i dodatki'),[t('1× smoke machine','1× wytwornica dymu'),t('1× Full HD projector','1× projektor Full HD'),t('1× fan','1× wentylator')]],
 [t('Stands & power','Statywy i zasilanie'),[t('3× C-stands with grip arms','3× C-stand + fajki'),t('1× boom stand on wheels','1× statyw boom na kółkach'),t('4× power strips / extension leads','4× listwy / przedłużacze'),t('5× NP-F batteries','5× baterie NP-F')]],
 ['Audio',[t('2× RØDE PodMic XLR microphones','2× mikrofon RØDE PodMic XLR'),'1× RØDE RØDECaster Pro II','2× RØDE PSA1 Studio Arm',t('2× SYNCO G2 receivers','2× SYNCO G2 odbiorniki'),t('1× SYNCO G2 transmitter','1× SYNCO G2 nadajnik')]],
 ] as [string,string[]][];
 const gallery=[['sets.jpg',t('Retro details and the book wall','Detale retro i ściana z książek')],['backdrop.jpg',t('Paper backdrop for photo sessions','Tło fotograficzne do sesji')],['furniture.jpg',t('Vintage furniture and curtains','Meble vintage i zasłony')],['mirror.jpg',t('Mirror, props and another angle on the room','Lustro, rekwizyty i kolejna perspektywa sali')],['book-wall.jpg',t('A characterful corner for portraits','Klimatyczny kącik do portretów')],['reception.jpg',t('Reception, make-up stations and changing room','Recepcja, stanowiska do makijażu i przebieralnia')]];
 return <>
 <section className="studio-new-hero"><Image src="/media/studio/main-room.jpg" alt={t('The vintage interior of Shalik Studio in Kraków','Wnętrze vintage Shalik Studio w Krakowie')} fill priority sizes="100vw"/><div className="studio-hero-overlay"/><div className="studio-hero-copy"><span className="eyebrow">SHALIK STUDIO / KRAKÓW</span><h1>{t('A space with','Przestrzeń z')}<br/><em>{t('a story to tell.','własną historią.')}</em></h1><p>{t('Retro interiors. Modern production possibilities. A 25 m² main room for photographs, films and conversations with character.','Wnętrza retro. Nowoczesne możliwości produkcji. Sala główna o powierzchni 25 m² do zdjęć, filmów i rozmów z charakterem.')}</p><a className="pill" href="#contact">{t('Enquire about a booking ↗','Zapytaj o rezerwację ↗')}</a></div></section>
 <div className="studio-facts"><span><strong>25 m²</strong>{t('Main shooting room','Główna sala zdjęciowa')}</span><span><strong>{t('Equipment included','Wyposażenie w cenie')}</strong>{t('Lighting, audio, costumes & props','Oświetlenie, audio, kostiumy i rekwizyty')}</span><span><strong>Kraków</strong>Rękawka 10/2</span></div>
 <section className="section studio-intro-new"><div><span className="eyebrow">{t('YOUR NEXT SET','TWÓJ KOLEJNY PLAN')}</span><h2>{t('Walk in.','Wejdź.')}<br/><span>{t('Find your frame.','Znajdź swój kadr.')}</span></h2></div><div><p>{t('Vintage furniture, rich fabrics and a wall of open books give each corner its own character. Create portraits, fashion editorials, interviews or a podcast with a setting that becomes part of the story.','Meble vintage, wyraziste tkaniny i ściana otwartych książek nadają każdemu kątowi własny charakter. Twórz portrety, sesje modowe, wywiady czy podcasty w otoczeniu, które staje się częścią opowieści.')}</p><p>{t('Beyond the 25 m² main room, prepare comfortably with a changing room, make-up stations, reception, coffee machine and WC. Lighting equipment, costumes and props are available to plan your setup.','Poza salą główną o powierzchni 25 m² czekają przebieralnia, stanowiska do makijażu, recepcja, ekspres do kawy i WC. Dostępne oświetlenie, kostiumy i rekwizyty pomogą zaplanować Twoją scenografię.')}</p></div></section>
 <section className="section studio-gallery-section" id="gallery"><div className="section-head"><span className="eyebrow">{t('EXPLORE THE SPACE','POZNAJ PRZESTRZEŃ')}</span><StudioInstagram/></div><div className="studio-photo-grid">{gallery.map(([file,caption],i)=><figure key={file}><a href={'/media/studio/'+file} target="_blank" rel="noopener noreferrer" aria-label={t('Open photo: ','Otwórz zdjęcie: ')+caption}><Image src={'/media/studio/'+file} alt={caption} width={file==='book-wall.jpg'?1280:1920} height={file==='book-wall.jpg'?1920:1280} sizes="(max-width: 700px) 100vw, 50vw"/></a><figcaption><span>0{i+1}</span>{caption}</figcaption></figure>)}</div></section>
 <section className="section studio-options"><span className="eyebrow">{t('CHOOSE YOUR SESSION','WYBIERZ SWOJĄ SESJĘ')}</span><h2>{t('Your idea. Your setup.','Twój pomysł. Twój plan.')}</h2><div className="studio-options-grid">{[[t('Photography','Fotografia'),t('Portraits, fashion, personal branding and creative sessions in a distinctive interior.','Portrety, moda, wizerunek i sesje kreatywne w charakterystycznym wnętrzu.')],[t('Film & interviews','Film i wywiady'),t('Build a scene using the vintage furniture, props and available continuous lighting.','Zbuduj scenę z mebli vintage, rekwizytów i dostępnego światła ciągłego.')],[t('Podcasts & videocasts','Podcasty i videocasty'),t('Record your conversation with available audio equipment. Ask about filming, editing and full production support.','Nagraj rozmowę z wykorzystaniem dostępnego sprzętu audio. Zapytaj o realizację wideo, montaż i pełne wsparcie produkcji.')]].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="section studio-pricing" id="pricing"><span className="eyebrow">{t('STUDIO RENTAL PRICES','CENNIK WYNAJMU STUDIA')}</span><h2>{t('Your time. Everything included.','Twój czas. Wszystko w cenie.')}</h2><p>{t('Rental includes the studio facilities, available lighting and audio equipment, costumes and props. Make-up services are priced separately.','Wynajem obejmuje zaplecze studia, dostępny sprzęt oświetleniowy i audio, kostiumy oraz rekwizyty. Usługa makijażu jest płatna osobno.')}</p><div className="studio-price-grid">{[['1 h','139 zł'],['2 h','258 zł'],['3 h','377 zł']].map(([hours,price])=><article key={hours}><h3>{hours}</h3><p className="studio-price">{price}</p><a className="text-link" href="#contact">{t('Enquire about a booking ↗','Zapytaj o rezerwację ↗')}</a></article>)}</div><p className="studio-extra-hour">{t('Each additional hour','Każda kolejna godzina')}: <strong>119 zł</strong></p><div className="studio-pricing-extras"><article><h3>{t('Events','Wydarzenia')}</h3><p>{t('Individual pricing. Tell us about your event, the number of guests and your preferred date.','Wycena indywidualna. Opowiedz nam o wydarzeniu, liczbie gości i preferowanym terminie.')}</p><a className="pill" href="#contact">{t('Contact us for event pricing ↗','Zapytaj o wycenę wydarzenia ↗')}</a></article><article><h3>{t('Make-up artist','Wizażystka / wizażysta')}</h3><p className="studio-price">{t('From 150 zł','Od 150 zł')}</p><p>{t('Add professional make-up to your session. Ask us to confirm availability and the final price for your needs.','Dodaj profesjonalny makijaż do swojej sesji. Zapytaj o dostępność i ostateczną cenę dopasowaną do Twoich potrzeb.')}</p><a className="text-link" href="#contact">{t('Ask about make-up ↗','Zapytaj o makijaż ↗')}</a></article></div></section>
<section className="section studio-equipment" id="equipment"><div className="heading-row"><div><span className="eyebrow">{t('PLAN YOUR LIGHT & SOUND','ZAPLANUJ ŚWIATŁO I DŹWIĘK')}</span><h2>{t('Equipment available.','Dostępny sprzęt.')}</h2></div><p>{t('Equipment is included in the rental price. Send us your equipment list so we can confirm availability for your session.','Sprzęt jest wliczony w cenę wynajmu. Prześlij listę potrzebnego wyposażenia, abyśmy mogli potwierdzić jego dostępność na Twoją sesję.')}</p></div><div className="studio-equipment-list">{equipment.map(([title,items])=><details key={title}><summary>{title}<span aria-hidden="true">+</span></summary><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></details>)}</div></section>
 
 
 
 <section className="section contact studio-reservation" id="contact"><span className="eyebrow">{t('BOOK YOUR NEXT SESSION','ZAREZERWUJ KOLEJNĄ SESJĘ')}</span><ContactForm studio/></section>
<section className="section studio-location"><div><span className="eyebrow">{t('FIND US IN KRAKÓW','ZNAJDZIESZ NAS W KRAKOWIE')}</span><h2>Shalik Studio</h2><address>Rękawka 10/2<br/>30-535 Kraków</address><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=R%C4%99kawka%2010%2F2%2C%2030-535%20Krak%C3%B3w" target="_blank" rel="noopener noreferrer">{t('Get directions ↗','Wyznacz trasę ↗')}</a></div><div className="studio-location-links"><a href="tel:+48731032536">+48 731 032 536</a><a href="mailto:contact@shalikvisual.com">contact@shalikvisual.com</a><StudioInstagram/><p>{t('Contact us before your visit to arrange access to the studio.','Przed wizytą skontaktuj się z nami, aby ustalić dostęp do studia.')}</p></div></section>
 </>;
}
