import { Header, Contact, Footer } from '../shared';
import { clientNames, businessClubs } from './names';
export const metadata = {title:'Clients & Partners — Shalik Visual',description:'Meet our clients, explore selected productions and discover our PKB and BNI business club memberships.'};
export default function Partners(){return <><Header/><main>
<section className="section partners-hero"><span className="eyebrow">SHALIK VISUAL / CLIENTS &amp; PARTNERS</span><h1>BUILT ON TRUST.<br/><em>CREATED TOGETHER.</em></h1><p>Behind every production is a relationship. Meet the clients who trust us with their stories and the business communities we are part of.</p><div className="relationship-actions"><a className="pill" href="#contact">Discuss your project ↗</a><a className="text-link" href="#network">Our business network ↓</a></div></section>
<section className="section partners-names" id="clients"><span className="eyebrow">OUR CLIENTS</span><h2>They trusted us.<br/><span>We brought their ideas to life.</span></h2><p>From artists and podcast creators to event organisers and businesses, these are the clients we have worked with.</p><ul className="client-names">{clientNames.map(name=><li key={name}>{name}</li>)}</ul>
<div className="client-projects"><article><span className="eyebrow">MUSIC VIDEO / FOBOS</span><h3>A debut with an impact.</h3><p>Three shooting days, four locations and a debut music video for the duo Fobos. Balerina reached more than 20,000 views in its first two months.</p><a className="text-link" href="/offer/music-videos#case-study">Explore the Fobos project ↗</a></article><article><span className="eyebrow">EVENT FILM / COBIN ANGELS</span><h3>The whole evening. One story.</h3><p>From the first arrivals to the final moments of Business Angel of the Year, we captured the event and delivered the finished film within 14 days.</p><a className="text-link" href="/offer/event-films#case-study">Explore the Cobin Angels project ↗</a></article><article><span className="eyebrow">POST-PRODUCTION / WHAI</span><h3>Long conversations, carefully shaped.</h3><p>A two-hour podcast episode shaped through editing, animation and a promotional trailer, with post-production completed in seven days.</p><a className="text-link" href="/offer/editing-post-production#case-study">Explore the WHAI project ↗</a></article></div></section>
<section className="section network-section" id="network"><span className="eyebrow">PARTNERS &amp; BUSINESS COMMUNITIES</span><h2>Our network.<br/><span>More possibilities.</span></h2><p>We are members of the PKB and BNI business clubs. Our involvement creates space to exchange experience, build professional relationships and explore new collaborations.</p><div className="network-cards">{businessClubs.map(name=><article key={name}><span className="eyebrow">BUSINESS CLUB MEMBERSHIP</span><h3>{name}</h3><p>Shalik Visual is a member of this business community.</p></article>)}</div></section>
<section className="section partnership-invite"><span className="eyebrow">LET’S CREATE TOGETHER</span><h2>Your next project<br/>starts with a conversation.</h2><p>Tell us what you want to create, who you want to reach and when you need it. Looking to collaborate as an agency or creative specialist? We would love to hear from you too.</p><div className="relationship-actions"><a className="pill dark" href="#contact">Discuss your project ↗</a><a className="text-link" href="mailto:contact@shalikvisual.com?subject=Partnership%20enquiry">Explore a partnership ↗</a></div></section><Contact/></main><Footer/></>}
