import { Header, Contact, Footer } from '../shared';
import { clientNames, businessClubs } from './names';
export const metadata = {title:"Klienci i partnerzy — Shalik Visual",description:"Poznaj naszych klientów, zobacz wybrane realizacje i dowiedz się o naszym członkostwie w klubach biznesowych PKB i BNI."};
export default function Partners(){return <><Header/><main>
<section className="section partners-hero"><span className="eyebrow">SHALIK VISUAL / KLIENCI I PARTNERZY</span><h1>OPARTE NA ZAUFANIU.<br/><em>TWORZONE WSPÓLNIE.</em></h1><p>Za każdą produkcją stoją relacje. Poznaj klientów, którzy powierzają nam swoje historie, oraz społeczności biznesowe, do których należymy.</p><div className="relationship-actions"><a className="pill" href="#contact">Porozmawiajmy o projekcie ↗</a><a className="text-link" href="#network">Nasza sieć biznesowa ↓</a></div></section>
<section className="section partners-names" id="clients"><span className="eyebrow">NASI KLIENCI</span><h2>Zaufali nam.<br/><span>Ich pomysły nabrały kształtu.</span></h2><p>Artyści, twórcy podcastów, organizatorzy wydarzeń i firmy — oto klienci, z którymi mieliśmy okazję pracować.</p><ul className="client-names">{clientNames.map(name=><li key={name}>{name}</li>)}</ul>
<div className="client-projects"><article><span className="eyebrow">TELEDYSK / FOBOS</span><h3>Debiut, który przyciąga uwagę.</h3><p>Trzy dni zdjęciowe, cztery lokalizacje i debiutancki teledysk duetu Fobos. Balerina zdobyła ponad 20 000 wyświetleń w ciągu pierwszych dwóch miesięcy.</p><a className="text-link" href="/pl/offer/music-videos#case-study">Zobacz projekt Fobos ↗</a></article><article><span className="eyebrow">FILM EVENTOWY / COBIN ANGELS</span><h3>Cały wieczór. Jedna historia.</h3><p>Od przybycia pierwszych gości po ostatnie chwile Business Angel of the Year — uwieczniliśmy wydarzenie i dostarczyliśmy gotowy film w ciągu 14 dni.</p><a className="text-link" href="/pl/offer/event-films#case-study">Zobacz projekt Cobin Angels ↗</a></article><article><span className="eyebrow">POSTPRODUKCJA / WHAI</span><h3>Długie rozmowy, dopracowana forma.</h3><p>Dwugodzinny odcinek podcastu, dopracowany montaż, animacje i zwiastun promocyjny. Postprodukcję zrealizowaliśmy w siedem dni.</p><a className="text-link" href="/pl/offer/editing-post-production#case-study">Zobacz projekt WHAI ↗</a></article></div></section>
<section className="section network-section" id="network"><span className="eyebrow">PARTNERZY I SPOŁECZNOŚCI BIZNESOWE</span><h2>Nasza sieć kontaktów.<br/><span>Więcej możliwości.</span></h2><p>Należymy do klubów biznesowych PKB i BNI. Nasze zaangażowanie daje przestrzeń do wymiany doświadczeń, budowania relacji zawodowych i odkrywania nowych możliwości współpracy.</p><div className="network-cards">{businessClubs.map(name=><article key={name}><span className="eyebrow">CZŁONKOSTWO W KLUBIE BIZNESOWYM</span><h3>{name}</h3><p>Shalik Visual należy do tej społeczności biznesowej.</p></article>)}</div></section>
<section className="section partnership-invite"><span className="eyebrow">TWÓRZMY RAZEM</span><h2>Twój kolejny projekt<br/>zaczyna się od rozmowy.</h2><p>Opowiedz nam, co chcesz stworzyć, do kogo dotrzeć i w jakim terminie. Reprezentujesz agencję lub działasz w branży kreatywnej? Porozmawiajmy również o wspólnej realizacji projektów.</p><div className="relationship-actions"><a className="pill dark" href="#contact">Porozmawiajmy o projekcie ↗</a><a className="text-link" href="mailto:contact@shalikvisual.com?subject=Zapytanie%20o%20wspolprace">Porozmawiajmy o współpracy ↗</a></div></section><Contact/></main><Footer/></>}
