import { notFound } from 'next/navigation';
import { Header, Contact, Footer } from '../../shared';
import { services, enquiry } from '../services';
export function generateStaticParams(){return services.map(s=>({service:s.slug}))}
export async function generateMetadata({params}:{params:Promise<{service:string}>}){const {service}=await params;const s=services.find(s=>s.slug===service);return {title:s?`${s.name} — Shalik Visual`:"Nie znaleziono usługi",description:s?.summary}}
export default async function Service({params}:{params:Promise<{service:string}>}){
 const {service}=await params;const s=services.find(s=>s.slug===service);if(!s)notFound();
 return <><Header/><main><section className="section offer-hero"><a className="eyebrow" href="/pl/#offer">← WSZYSTKIE USŁUGI</a><div className="offer-hero-grid"><div><p className="eyebrow offer-accent">{s.name.toUpperCase()}</p><h1>{s.headline}</h1></div><div><p className="offer-lead">{s.summary}</p><p>{s.audience}</p><a className="pill dark" href={enquiry(s.name)}>Porozmawiajmy o projekcie ↗</a></div></div><nav className="service-sections" aria-label="Na tej stronie"><a href="#included">Zakres usługi</a><a href="#examples">Nasze realizacje</a><a href="#process">Przebieg współpracy</a><a href="#pricing">Cennik</a><a href="#case-study">Przykładowy projekt</a></nav></section>
 <section className="section offer-split" id="included"><div><span className="eyebrow">01 / ZAKRES USŁUGI</span><h2>Czym możemy<br/>się zająć.</h2><p>Dopasujemy zakres prac do Twojego projektu. Wycena określi materiały końcowe, harmonogram i liczbę rund poprawek.</p></div><ol className="included-list">{s.includes.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol></section>
 <section className="section service-work" id="examples"><div className="heading-row"><div><span className="eyebrow">02 / NASZE REALIZACJE</span><h2>Zobacz, jak tworzymy.</h2></div><p>Obejrzyj nasz showreel.<br/>Napisz do nas, aby zobaczyć realizacje odpowiadające Twojemu briefowi.</p></div><video controls playsInline preload="none" poster="/media/frame-1.jpg" src="/media/showreel.mp4" aria-label="Showreel produkcyjny Shalik Visual"/><div className="card-label"><h3>Shalik Visual / Showreel produkcyjny</h3><a href={enquiry(s.name)}>Zapytaj o podobne realizacje ↗</a></div></section>
 <section className="section" id="process"><span className="eyebrow">03 / JAK WSPÓŁPRACUJEMY</span><h2 className="service-heading">Od Twojego briefu<br/>po gotowy materiał.</h2><ol className="process-grid">{s.steps.map((step,i)=><li key={step}><span className="process-number">0{i+1}</span><h3>{["Zaczynamy od rozmowy","Ustalamy plan","Tworzymy razem","Dopracowujemy i oddajemy"][i]}</h3><p>{step}</p></li>)}</ol></section>
 <section className="section pricing-section offer-split" id="pricing"><div><span className="eyebrow">04 / CENNIK</span><h2>Jasny zakres.<br/>Indywidualna wycena.</h2><p>Każdy projekt ma inne potrzeby. Prześlij brief i orientacyjny budżet, a zaproponujemy odpowiedni zakres prac.</p></div><div className="quote-panel"><span className="eyebrow">{s.name.toUpperCase()}</span><h3>Wycena indywidualna</h3><p><strong>Co wpływa na budżet</strong><br/>{s.factors}</p><p><strong>Zanim rozpoczniemy produkcję</strong><br/>W wycenie ustalamy materiały końcowe, prawa do wykorzystania, harmonogram, rundy poprawek i ewentualne koszty dodatkowe.</p><a className="pill dark" href={enquiry(s.name)}>Poproś o wycenę projektu ↗</a></div></section>
 <section className="section" id="case-study"><span className="eyebrow">05 / PRZYKŁADOWY PROJEKT</span><div className="heading-row"><h2>Tak może wyglądać<br/>nasza współpraca.</h2><p>Przykładowy scenariusz projektu.<br/>To ilustracja zakresu, a nie zrealizowany projekt ani deklaracja wyników.</p></div><div className="case-grid">{[["Brief",s.brief],["Podejście",s.approach],["Materiały końcowe",s.delivery]].map(([title,text])=><article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="section other-services"><span className="eyebrow">POZNAJ POZOSTAŁE USŁUGI</span><div>{services.filter(x=>x.slug!==s.slug).map(x=><a href={"/pl/offer/"+x.slug} key={x.slug}>{x.name} ↗</a>)}</div></section><Contact/></main><Footer/></>
}
